services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
  test-db:
    container_name: test_db_container
    image: postgres
    environment:
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
      PGPORT: ${TEST_DB_PORT}
    ports:
      - ${TEST_DB_PORT}:${TEST_DB_PORT}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
